### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by hktalent** [eps696/aphantasia#44]
Mac OS,python3
```
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/ai/aphantasia/illustrip.py", line 511, in <module>
    main()
  File "/Users/51pwn/MyWork/ai/aphantasia/illustrip.py", line 243, in main
    key_txt_encs = [enc_text(txt) for txt in texts]
  File "/Users/51pwn/MyWork/ai/aphantasia/illustrip.py", line 243, in <listcomp>
    key_txt_encs = [enc_text(txt) for txt in texts]
  File "/Users/51pwn/MyWork/ai/aphantasia/illustrip.py", line 203, in enc_text
    emb = model_clip.encode_text(clip.tokenize(subtxt).cuda()[:77])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by eps696** [comment]
this repo relies on CUDA and requires supported GPU hardware [from this list https://developer.nvidia.com/cuda-gpus], which are obviously missed on macs. 
you may use online Colab versions instead.
